# Generated by Django 5.2.8 on 2025-12-01 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_contacto_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='persona.persona'),
        ),
    ]
